[package]
name = "yari-py"
version = "0.2.1"
description = "Python bindings for YARI."
authors = ["Matej Kastak <matej.kastak@avast.com>"]
edition = "2021"
license = "MIT"

[lib]
name = "yari"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
yari-sys = { path = "../yari-sys" }
